services:
  postgres-dev:
    extends:
      file: services.yaml
      service: postgres
    container_name: db-dev
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app_network

  keycloak-postgres-dev:
    extends:
      file: services.yaml
      service: postgres
    container_name: keycloak-db-dev
    environment:
      POSTGRES_DB: keycloak_dev
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: devsecret
    ports:
      - '5433:5432'
    volumes:
      - keycloak-postgres-dev-data:/var/lib/postgresql/data
    labels:
      org.springframework.boot.ignore: "true"
    networks:
      - app_network

  keycloak-dev:
    extends:
      file: services.yaml
      service: keycloak
    container_name: keycloak-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db-dev
      KC_DB_URL_DATABASE: keycloak_dev
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: devsecret
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "9000:8080"
    depends_on:
      - keycloak-postgres-dev
    volumes:
      - ./build/libs/:/opt/keycloak/providers/
      - ./demo/:/opt/keycloak/data/import
    networks:
      - app_network

  eureka-server-dev:
    extends:
      file: services.yaml
      service: eureka-server
    container_name: eureka-server-dev
    pull_policy: always
    ports:
      - "8761:8761"
    networks:
      - app_network

  cloud-config-server-dev:
    extends:
      file: services.yaml
      service: cloud-config-server
    container_name: cloud-config-server-dev
    env_file:
      - .env
    environment:
      EUREKA_URI: http://eureka-server-dev:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME: aquadevv
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${GITHUB_TOKEN}
    depends_on:
      eureka-server-dev:
        condition: service_healthy
    pull_policy: always
    ports:
      - "8888:8888"
    networks:
      - app_network

  api-gateway-dev:
    extends:
      file: services.yaml
      service: api-gateway
    container_name: api-gateway-dev
    environment:
      EUREKA_URI: http://eureka-server-dev:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak-dev:9000/realms/dev
    depends_on:
      eureka-server-dev:
        condition: service_healthy
      cloud-config-server-dev:
        condition: service_healthy
      keycloak-dev:
        condition: service_started
    pull_policy: always
    ports:
      - "9191:9191"
    networks:
      - app_network

  user-service-dev:
    extends:
      file: services.yaml
      service: user-service
    container_name: user-service-dev
    env_file:
      - .env
    environment:
      EUREKA_URI: http://eureka-server-dev:8761/eureka
      KEYCLOAK_URI: http://keycloak-dev:9000
      DB_HOST: postgres-dev
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      api-gateway-dev:
        condition: service_healthy
      eureka-server-dev:
        condition: service_healthy
      cloud-config-server-dev:
        condition: service_healthy
      keycloak-dev:
        condition: service_started
    pull_policy: always
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres-dev-data:
  keycloak-postgres-dev-data:

networks:
  app_network:
    driver: bridge