server:
  port: 8080

spring:
  application:
    name: user-service
  docker:
    compose:
      file: docker-compose-dev.yaml
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/dev
  config:
    import: optional:classpath:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: http://localhost:9000
  realm: dev
  resource: user-service
  credentials:
    secret: ${KEYCLOAK_USER_SERVICE_SECRET}

