spring:
  application:
    name: user-service

  config:
    import: "configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,bus-refresh