name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_BASE
        run: |
          IMAGE_BASE="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_BASE:$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_NAME_LATEST=$IMAGE_BASE:latest" >> $GITHUB_ENV

      - name: Build build in docker
        run: |
          docker build -t ${IMAGE_BASE}:${IMAGE_TAG} .

      - name: Tag image as latest and push
        run: |
          docker tag ${IMAGE_BASE}:${IMAGE_TAG} $IMAGE_NAME_LATEST
          docker push $IMAGE_NAME_LATEST

      - name: Confirm published images
        run: |
          echo "Published: $IMAGE_NAME"
          echo "Published: $IMAGE_NAME_LATEST"
